version: '3'
services:
  xrpl-server:
    container_name: 'xrpl-server'
    hostname: 'xrpl.proxi.lan'
    image: xrpl:latest
    restart: always
    build:
      context: .
    ports:
      - '5005:5005'
      - '6006:6006'
networks:
  default:
    external: true
    name: proxi-network