version: '3'
services:
  xrpl-server:
    container_name: 'xrpl-server'
    image: xrpl:latest
    restart: always
    privileged: true
    build:
      context: .
    ports:
      - '5005:5005'
      - '6005:6005'