version: '3.5'
services:
  load_balancer:
    container_name: 'nginx'
    image: nginx
    build:
      context: .
    # Port mapping, external_port:internal_port
    ports:
      - '80:80'
      - '8080:8080'
      - '443:443'
networks:
  default:
    name: proxi-network